// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'block': string;
  'name': string;
  'number': string;
  'rating': string;
  'report': string;
  'tableBlock': string;
  'tableRating': string;
  'tableReport': string;
}
export const cssExports: CssExports;
export default cssExports;
