// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addReportBtn': string;
  'content': string;
  'contentWrapper': string;
  'desktop': string;
  'menu': string;
  'menuGroup': string;
}
export const cssExports: CssExports;
export default cssExports;
