// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonTags': string;
  'footer': string;
  'nameAndDate': string;
  'reportItem': string;
  'status': string;
  'tags': Array<string>;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
