// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'image': string;
  'imagesList': string;
  'loadImg': string;
  'remove': string;
}
export const cssExports: CssExports;
export default cssExports;
