// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comment': string;
  'data': string;
  'name': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
